<?php

$data = [
    ["id"=>1, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>2, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>3, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>4, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>5, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>6, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>7, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>8, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>9, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>10, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>11, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>12, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>13, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>14, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>15, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>16, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>17, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>18, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>19, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>20, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>21, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>22, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>23, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>24, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>25, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>26, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>27, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>28, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>29, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>30, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>31, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>32, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."],
    ["id"=>33, "title"=>"情人节礼物、历史新低：ASPINAL of LONDON CHELSEA 女士切尔西真皮斜挎包","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/62.jpg","author"=>"推荐人：薄荷绿1314","renwu"=>"英国馆","liwu"=>"情人节礼物","jingzhi"=>"精致小巧，低调奢华，简约翻盖风琴包，包直邮好价~","pinpai"=>"说起英国品牌Aspinal of London也许大家还有些陌生，但是如果提到KATE王妃在订婚宴上拿的经典U型..."],
    ["id"=>34, "title"=>"LG 38UC99-W 38英寸 IPS曲面显示器（3840×1600、FreeSync、75Hz）","baoyou"=>"£210.8包直邮（需用码，约￥1900）","img"=>"./image/63.jpg","author"=>"推荐人：tonywang88","liwu"=>" 年货节显示器","jingzhi"=>"4K级带鱼屏，99% sRGB色域。","pinpai"=>"LG 38UC99-W是一款罕见的使用38英寸屏幕的21：9比例显示器，属于同时期市售产品中最大的“带鱼屏”。使用的应是自家..."]
        ];
$page = $_GET['pagenation']?$_GET['pagenation']:1;
$newArr = array_slice($data,($page-1)*5,5);
echo json_encode($newArr);